version: "3.4"

services:
  danbooru:
    user: root
    image: danbooru
    hostname: aibooru.online
    env_file: .env.local
    volumes:
      - "danbooru-images:/danbooru/public/data"
      - "./config/danbooru_local_config.rb:/danbooru/config/danbooru_local_config.rb:ro"
    tmpfs:
      - /tmp
    depends_on:
      - postgres
    command: ["bash", "-c", "bin/rails db:prepare && bin/rails db:seed && bin/rails server -b 0.0.0.0"]
    restart: always

  cron:
    user: root
    image: danbooru
    env_file: .env.local
    depends_on:
      - danbooru
    volumes:
      - "danbooru-images:/danbooru/public/data"
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/rails danbooru:cron"]
    restart: always

  jobs:
    # We need root to write temp upload files in the images directory (/danbooru/public/data)
    user: root
    image: danbooru
    hostname: aibooru.online
    env_file: .env.local
    depends_on:
      - danbooru
    volumes:
      # We need access to images so we can add/remove images to IQDB.
      - "danbooru-images:/danbooru/public/data"
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/good_job start"]
    restart: always

  # https://github.com/danbooru/iqdb
  # https://hub.docker.com/repository/docker/evazion/iqdb
  iqdb:
    image: evazion/iqdb
    volumes:
      - "iqdb-data:/iqdb/data"
    command: ["http", "0.0.0.0", "5588", "/iqdb/data/iqdb.sqlite"]
    restart: always

  redis:
    image: redis
    restart: always

  postgres:
    image: evazion/postgres
    environment:
      POSTGRES_USER: danbooru
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "danbooru-data:/var/lib/postgresql/data"
    restart: always

  nginx:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=aibooru.online
      - VALIDATION=http
    ports:
      - 80:80
      - 443:443
    volumes:
      - "danbooru-images:/danbooru-images/data:ro"
      - ./nginx-config:/config
    restart: always

  nginx:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=aibooru.online
      - VALIDATION=http
    ports:
      - 443:443
      - 80:80
    volumes:
      - "danbooru-images:/danbooru-images"
      - ./nginx-config:/config

volumes:
  danbooru-images:
    name: danbooru-images
  danbooru-data:
    name: danbooru-data
  iqdb-data:
    name: iqdb-data
